os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: "9.1.0"

cache:
  - .eslintcache
  - node_modules
  - '%USERPROFILE%\.electron'

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g yarn@1.3.2
  - npm install -g electron-forge
  - git submodule update --init --recursive
  - yarn install --force

build_script:
  - electron-forge make --platform=win32

deploy:
  release: voyer-auto-release-example-v$(appveyor_build_version)
  description: 'voyer release on tag example'
  provider: GitHub
  auth_token:
    secure: 3n1+WM1/Z6YLaXTWYyxNoTK1EvcPt8f73KzFaMXElc9rKUefBJevlOmhh0qE+qGe
  artifact: /out/.*\.*/
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
